[General]
skip-proxy = 192.168.0.0/24, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local
exclude-simple-hostnames = true
internet-test-url = http://taobao.com/
proxy-test-url = http://www.apple.com/
test-timeout = 2
dns-server = 223.5.5.5, 114.114.114.114
# encrypted-dns-server = https://223.5.5.5/ // 除非当地 ISP 有严重的 DNS 污染问题，否则没必要开启 DoH，传统 DNS 的性能最优，网络异常后恢复速度最快

# 增强版 Wi-Fi 助理（iOS）
# Surge 会在 Wi-Fi 网络不佳时尝试使用数据网络建立连接。该功能将对所有连接生效，请仅当使用不限量的数据流量时开启。
wifi-assist = true
ipv6 = false

[Proxy]
#!include proxy.dconf.conf

[Proxy Group]
🚀自动选择 = select, REJECT
🎯手动选择 = select, REJECT
⛔️禁止访问 = select, REJECT

🇺🇲美国节点 = select, REJECT
🇯🇵日本节点 = select, REJECT
🇭🇰香港节点 = select, REJECT

🌀人工智能 = select, REJECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/since2006/surge/main/rule/cn.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/since2006/surge/main/rule/blocked.list,🚀自动选择
RULE-SET,https://raw.githubusercontent.com/since2006/surge/main/rule/us.list,🇺🇲美国节点
RULE-SET,https://raw.githubusercontent.com/since2006/surge/main/rule/jp.list,🇯🇵日本节点
RULE-SET,https://raw.githubusercontent.com/since2006/surge/main/rule/hk.list,🇭🇰香港节点
DOMAIN,apps.apple.com,🚀自动选择
DOMAIN-SUFFIX,ls.apple.com,DIRECT // Apple Maps
DOMAIN-SUFFIX,store.apple.com,DIRECT // Apple Store Online
RULE-SET,SYSTEM,🚀自动选择
RULE-SET,https://raw.githubusercontent.com/since2006/surge/main/rule/apple.list,🚀自动选择
# 以下规则将触发本地 DNS 解析
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,🚀自动选择,dns-failed
